### ISSUE TITLE
Page cover up bug on load asset

### ISSUE THREAD

**Issue by oelbaga** [Cockpit-HQ/Cockpit#197]
I often get this bug on the latest cockpit version. The page goes blurry and blank whenever I click anything to start adding an asset. It blocks the page and I have to refresh the page to get it working again and then I lose all my data entries. It seems to happen often on first load. I can’t identify what triggers it, it happens all the time on random clicks to add an asset. 

![image](https://github.com/user-attachments/assets/84fec4dc-31cf-4776-a1db-bedb23ebf11e)

![image](https://github.com/user-attachments/assets/529455f9-067d-4efc-b6a5-25d21486a93b)

**Comment by aheinze** [comment]
Do you get any errors in the js console which you can share?

**Comment by oelbaga** [comment]
Yes I found the console log errors here. This happens randomly when clicking to add an asset:

<img width="1104" alt="Screenshot 2024-07-23 at 10 55 01 AM" src="https://github.com/user-attachments/assets/01dbe71a-db9c-45e8-9ef3-8e3f3270cc27">

**Comment by BimaBizz** [comment]
> Do you get any errors in the js console which you can share? Also can you try to clear your browser cache?
hey [aheinze](https://github.com/aheinze) i do get same error, but after i downgrade it's work again

**Comment by aheinze** [comment]
which browser are you using?

**Comment by BimaBizz** [comment]
i use google chrome and share hosting

**Comment by oelbaga** [comment]
It happens on all browsers. I tested.

**Comment by aheinze** [comment]
Can you try the latest [dev release](https://files.getcockpit.com/?dir=releases/develop)? Thanks!

**Comment by oelbaga** [comment]
I don't want to use something that isn't ready for production yet but if this eventually gets released with the fix I would love to know!

**Comment by Yohan-U** [comment]
Hello,
We are facing the same issue here, but in an other use case.
When we add a component, we correctly get the components panel.

![components_ok](https://github.com/user-attachments/assets/6b551b0e-08b0-466a-b6c5-1654b96d6f8d)

Then close the component panel, go on an other browser tab or reduce the current browser window.
Finaly try to add a component again, the components panel show nothing.

![components_ko](https://github.com/user-attachments/assets/aa45b6f7-9e98-4fad-b80c-d5d27376c550)

The console logs look pretty similar to what was shared before.
Our assumption is that the bug is related to the way the browser local storage is managed. It seems that the local storage is cleared because of the manipulations of the browser, and then the bug appears.

Interesting workaround in our case : if you use the "copy a component" feature first, you can't reproduce the pattern then. As if filling the local storage by yourself is fixing the bug.

This bug appeared in the version 2.8.5 (on which I reproduced this pattern).
And developers on my team think that the file "addons/Layout/assets/vue-components/layout/component-picker.js", changed on the 2.8.5 version, could be a good place to take a look.

This bug makes the work of our Cockpit users actually really painful in a day to day use.
I hope it will help to find a fix. And will be happy to share more details if needed.
Thanks!

**Comment by aheinze** [comment]
@Yohan-U Is there a chance that you can try the latest [dev release](https://files.getcockpit.com/?dir=releases/develop) and verify that the issue is fixed? Thanks!

**Comment by aheinze** [comment]
v2.9.0 was just released which should come with a fix

**Comment by oelbaga** [comment]
Where can you check the cockpit version in the files?

**Comment by aheinze** [comment]
settings > system info

**Comment by Yohan-U** [comment]
> v2.9.0 was just released which should come with a fix

@aheinze Great!
We didn't have time to test the dev release yet. But we will check the v2.9.0 then.
Thank you for the update.

**Comment by oelbaga** [comment]
> settings > system info

Thank you, but I mean in the downloaded files of the repo itself. Where does it show the version in the code base?

**Comment by Yohan-U** [comment]
> v2.9.0 was just released which should come with a fix

@aheinze After an upgrade to the version 2.9.0, I confirm the bug is gone for us.
Thanks a lot!
