### ISSUE TITLE
Asset preview image never generated (jpg being mistaken for avif)

### ISSUE THREAD

**Issue by ebrenner-code** [Cockpit-HQ/Cockpit#50]
After uploading an image, a preview is never generated. However, the image is uploaded and can be fetched/altered via the api.

Attempting to upload an image throws "PHP Warning:  imageavif(): AVIF image support has been disabled" in /lib/SimpleImageLib.php on line 182

The image is a jpg. Even the cockpit api lists the mimetype as image/jpeg. So the switch statement in SimpleImage seems to be working and I assume the issue is with detecting the mimetype

**Comment by aheinze** [comment]
Thanks for reporting! Avif support was removed recently - see the commit [here](https://github.com/Cockpit-HQ/Cockpit/commit/a65e1f64379389f6d2a8bea54d725d31db419242)

**Comment by ebrenner-code** [comment]
Yes, but the issue is I uploaded a JPG and received that error

**Comment by aheinze** [comment]
Yes, and it was due to this [lines](https://github.com/Cockpit-HQ/Cockpit/commit/a65e1f64379389f6d2a8bea54d725d31db419242#diff-aac3ac1eb6ae1a4479a603300712c152a172a68c6e06ec75d1410233a929057eL267-L270)

the preview in the admin backend always requests a thumbnail with `mime=auto` which tries to guess the best format supported by the browser. But avif support still looks pretty unstable, so I removed it again.

**Comment by ebrenner-code** [comment]
Understood, can confirm it is working now. Thanks!
